### ISSUE TITLE
Generate map objects with nested Konstan variables

### ISSUE THREAD

**Issue by fforget** [absolunet/nwayo#45]
Example use case with breakpoints :

```yaml
nav:
  size:
    small: 50
    medium: 60
    large: 70
```
Would result like this in the konstan scss file :
```scss
$konstan-nav-size-small: 50;
$konstan-nav-size-medium: 60;
$konstan-nav-size-large: 70;
$konstan-nav-size: (
  small: 50,
  medium: 60,
  large: 70
);
```
